#161340185 Ft favorite articles
andela/ah-backend-odin pull request #34
Opened 2018-11-13 16:02 UTC by JSnakegitHub

#### What does this PR do?
This PR allows users to mark an article as their favorite.
#### Description of Task to be completed?
The user needs to be logged in in order to favorite an article
#### How should this be manually tested?
Run the server and do the following:
1. To favorite an article, 
- Go to postman
- Visit the URL `http://127.0.0.1:8000/api/articles/<slug>/favorites/` Where <slug> is the slug of the article. 
- Provide the value True to favorite the article and hit POST
2. To view all the articles with their favorite status
- Visit the URL `http://127.0.0.1:8000/api/articles/whats-up-88206391171c/favorites/` and hit a GET
#### Any background context you want to provide?
-By default, the status of all articles is set to False.  It is only true when u make it True
#### What are the relevant pivotal tracker stories?
[#161340185](https://www.pivotaltracker.com/story/show/161340185)
#### Screenshots (if appropriate)
1. Post response for favoriting the article
<img width="967" alt="post" src="https://user-images.githubusercontent.com/20398831/48425719-703cf380-e776-11e8-9442-ac4b7446f8e2.png">
2. Get articles with their status
<img width="959" alt="get" src="https://user-images.githubusercontent.com/20398831/48425826-a67a7300-e776-11e8-8f90-ad9861b2ee4a.png">

#### Questions:

2018-11-13 20:01 UTC, krmroland requested changes

2018-11-13 20:01 UTC, krmroland commented on authors/apps/articles/views.py
> +        token = request.META.get('HTTP_AUTHORIZATION', " ").split(' ')[1]
This works fine, but since we already have a `JWTAuthentication`, it would violate the DRY principle to do the JWT authentication here again.
 
If you want to get the authenticated user, just include the `IsAuthenticated` permission in your permissions and then grab the authenticated user from the current request like

```python
user_instance = request.user
```

2018-11-13 20:01 UTC, krmroland commented on authors/apps/articles/views.py
> +        data["message"] = "You Have Successfully Added This Article To Your Favorites"
It would also be better to do this sort of data shaping in the render's since you already have one.

2018-11-15 09:57 UTC, JSnakegitHub commented on authors/apps/articles/views.py
> +        token = request.META.get('HTTP_AUTHORIZATION', " ").split(' ')[1]
Thanks, working on it

2018-11-15 17:24 UTC, closed without merging