#161340167 Integrate travis with a readme badge
andela/ah-backend-odin pull request #6
Opened 2018-10-24 07:38 UTC by nakatuddesuzan

#### What does this PR do?
Integrate Travis  with a readme badge
#### Description of Task to be completed?
Added Travis.yml file
Added Travis badge to the Readme file
#### What are the relevant pivotal tracker stories?
[#161340167](https://www.pivotaltracker.com/story/show/161340167)

2018-10-29 09:03 UTC, daud1 commented on .travis.yml
> +- "3.7"
Python3.7 is not yet supposed by most build tools because it is pretty recent.
Please change this to a stable version of Python.

2018-10-29 09:04 UTC, daud1 requested changes
Python3.7 is not yet supposed by most build tools because it is pretty recent.
Please change this to a stable version of Python.

2018-10-29 09:04 UTC, daud1 commented on .travis.yml
> +- "3.7"
Python3.7 is not yet supposed by most build tools because it is pretty recent.
Please change this to a stable version of Python.

2018-10-29 12:46 UTC, krmroland reviewed
Insight

2018-10-29 12:46 UTC, krmroland commented on README.md
> +[![Build Status](https://travis-ci.org/andela/ah-backend-odin.svg?branch=develop)](https://travis-ci.org/andela/ah-backend-odin)
The travis badge is currently pointing to the develop branch, which i think is okay.  My question is if the master(stable branch) should be displaying the develop build's badge.

2018-10-30 12:27 UTC, daud1 approved these changes

2018-10-30 12:28 UTC, merged